const fs = require('fs');
const path = require('path');
const pdfParse = require('pdf-parse');
const Document = require('../models/documentModel');
const { parseWordDocumentStructure } = require('../services/wordParserService');
const { parsePdfDocumentStructure } = require('../services/pdfParserService');
const { exportAssessmentScheduleToExcel, generateCostAnalysisExcel } = require('../services/excelService');

// 上传文档处理函数
async function uploadDocument(req, res) {
  try {
    if (!req.file) {
      return res.status(400).json({
        success: false,
        message: '没有上传文件'
      });
    }

    const { documentType } = req.body; // 前端会传 'ClinicalProtocol'
    
    console.log('收到Clinical Protocol文件:', req.file.originalname, '类型:', req.file.mimetype);

    // 解析文档内容
    let parseResult = {
      extractedText: '',
      sectionedText: [],
      tables: [],
      parseInfo: {
        hasStructuredContent: false,
        sectionsCount: 0,
        tablesCount: 0,
        parseMethod: 'raw-text'
      }
    };
    
    try {
      if (req.file.mimetype === 'application/pdf') {
        // PDF结构化解析（使用新的多层算法）
        console.log('📄 开始PDF文档结构化解析...');
        parseResult = await parsePdfDocumentStructure(req.file.path);
        
        console.log(`✅ PDF解析完成 - 章节: ${parseResult.parseInfo.sectionsCount}, 表格: ${parseResult.parseInfo.tablesCount}`);
        
      } else if (req.file.mimetype === 'application/vnd.openxmlformats-officedocument.wordprocessingml.document') {
        // Word (.docx) 结构化解析
        console.log('📝 开始Word文档结构化解析...');
        parseResult = await parseWordDocumentStructure(req.file.path);
        
        console.log(`✅ Word解析完成 - 章节: ${parseResult.parseInfo.sectionsCount}, 表格: ${parseResult.parseInfo.tablesCount}`);
        
      } else if (req.file.mimetype === 'application/msword') {
        // 老版本Word (.doc) - 简单处理
        const fileBuffer = fs.readFileSync(req.file.path);
        parseResult.extractedText = fileBuffer.toString('utf8');
        parseResult.parseInfo.parseMethod = 'doc-simple';

        console.log('📄 老版本Word解析完成');
      }
    } catch (parseError) {
      console.warn('文档解析失败:', parseError.message);
      // parseResult 保持默认值（空内容）
    }

    // 解析项目选择数据
    let projectSelection = null;
    if (req.body.projectSelection) {
      try {
        projectSelection = JSON.parse(req.body.projectSelection);
        console.log('📋 项目选择数据:', projectSelection);
      } catch (parseError) {
        console.warn('⚠️ 项目选择数据解析失败:', parseError.message);
      }
    }

    // 创建文档记录 - 包含结构化数据
    const document = new Document({
      originalName: req.file.originalname,
      fileName: req.file.filename,
      filePath: req.file.path,
      fileSize: req.file.size,
      mimeType: req.file.mimetype,
      protocolType: 'ClinicalProtocol',
      extractedText: parseResult.extractedText,
      sectionedText: parseResult.sectionedText,
      tables: parseResult.tables,
      assessmentSchedule: parseResult.assessmentSchedule,
      sdtmAnalysis: parseResult.sdtmAnalysis, // 🔥 添加SDTM分析结果
      projectSelection: projectSelection, // 🔥 添加项目选择数据
      parseInfo: parseResult.parseInfo,
      specificMetadata: {} // 暂时为空，后续可用于存储解析出的临床数据
    });

    const savedDocument = await document.save();

    console.log('✅ Clinical Protocol 文档保存成功，ID:', savedDocument._id);
    console.log(`📊 保存的数据结构:`, {
      sections: parseResult.parseInfo.sectionsCount,
      tables: parseResult.parseInfo.tablesCount,
      hasStructuredContent: parseResult.parseInfo.hasStructuredContent,
      hasAssessmentSchedule: parseResult.parseInfo.hasAssessmentSchedule,
      method: parseResult.parseInfo.parseMethod
    });

    // 🔥 自动生成Excel文件
    let autoGeneratedExcel = null;
    let costAnalysisExcel = null;
    
    // 1. 生成评估时间表Excel（如果找到了评估时间表）
    if (parseResult.parseInfo.hasAssessmentSchedule && parseResult.assessmentSchedule) {
      try {
        console.log('📊 检测到评估时间表，开始自动生成Excel...');
        
        const targetDir = path.join(__dirname, '..', 'ScheduleOfAssessment');
        autoGeneratedExcel = exportAssessmentScheduleToExcel(
          parseResult.assessmentSchedule.htmlContent,
          savedDocument.originalName,
          targetDir
        );
          
        console.log(`✅ 评估时间表Excel自动生成成功: ${autoGeneratedExcel.filePath}`);
      } catch (excelError) {
        console.warn('⚠️ 自动生成评估时间表Excel失败:', excelError.message);
        // 不影响文档上传的主流程
      }
    }
    
    // 2. 生成成本分析Excel（基于项目选择）
    if (projectSelection) {
      try {
        console.log('📊 检测到项目选择，开始生成成本分析Excel...');
        
        const costAnalysisDir = path.join(__dirname, '..', 'CostAnalysis');
        costAnalysisExcel = generateCostAnalysisExcel(
          projectSelection,
          savedDocument.originalName,
          costAnalysisDir
        );
          
        console.log(`✅ 成本分析Excel自动生成成功: ${costAnalysisExcel.filePath}`);
      } catch (excelError) {
        console.warn('⚠️ 自动生成成本分析Excel失败:', excelError.message);
        // 不影响文档上传的主流程
      }
    }

    res.json({
      success: true,
      message: 'Clinical Protocol 上传成功',
      uploadId: savedDocument._id,
      fileName: req.file.originalname,
      fileSize: req.file.size,
      extractedLength: parseResult.extractedText.length,
      protocolType: 'ClinicalProtocol',
      structuredData: {
        sectionsCount: parseResult.parseInfo.sectionsCount,
        tablesCount: parseResult.parseInfo.tablesCount,
        hasStructuredContent: parseResult.parseInfo.hasStructuredContent,
        hasAssessmentSchedule: parseResult.parseInfo.hasAssessmentSchedule,
        parseMethod: parseResult.parseInfo.parseMethod,
        assessmentSchedule: parseResult.assessmentSchedule ? {
          tableIndex: parseResult.assessmentSchedule.tableIndex,
          confidence: parseResult.assessmentSchedule.confidence,
          identifiedBy: parseResult.assessmentSchedule.identifiedBy
        } : null
      },
      // 🔥 添加SDTM分析结果
      sdtmAnalysis: parseResult.sdtmAnalysis,
      // 🔥 项目选择信息
      projectSelection: projectSelection,
      // 🔥 自动生成的Excel文件信息
      autoGeneratedExcel: autoGeneratedExcel,
      costAnalysisExcel: costAnalysisExcel
    });

  } catch (error) {
    console.error('Clinical Protocol 上传错误:', error);
    
    // 清理临时文件
    if (req.file && fs.existsSync(req.file.path)) {
      fs.unlinkSync(req.file.path);
    }

    res.status(500).json({
      success: false,
      message: 'Clinical Protocol 上传失败',
      error: error.message
    });
  }
}

// 获取文档列表
async function getDocuments(req, res) {
  try {
    const documents = await Document.find({ protocolType: 'ClinicalProtocol' })
      .select('originalName fileSize uploadedAt protocolType specificMetadata parseInfo sectionedText tables assessmentSchedule')
      .sort({ uploadedAt: -1 });

    // 为每个文档添加结构化数据的摘要信息
    const documentsWithSummary = documents.map(doc => ({
      _id: doc._id,
      originalName: doc.originalName,
      fileSize: doc.fileSize,
      uploadedAt: doc.uploadedAt,
      protocolType: doc.protocolType,
      specificMetadata: doc.specificMetadata,
      structuredInfo: {
        hasStructuredContent: doc.parseInfo?.hasStructuredContent || false,
        sectionsCount: doc.parseInfo?.sectionsCount || 0,
        tablesCount: doc.parseInfo?.tablesCount || 0,
        parseMethod: doc.parseInfo?.parseMethod || 'unknown',
        sectionTitles: doc.sectionedText?.map(section => section.title) || [],
        hasExtractedText: !!doc.extractedText,
        hasAssessmentSchedule: doc.parseInfo?.hasAssessmentSchedule || false,
        assessmentSchedule: doc.assessmentSchedule ? {
          tableIndex: doc.assessmentSchedule.tableIndex,
          confidence: doc.assessmentSchedule.confidence,
          identifiedBy: doc.assessmentSchedule.identifiedBy
        } : null
      }
    }));

    res.json({
      success: true,
      message: '获取文档列表成功',
      documents: documentsWithSummary
    });

  } catch (error) {
    console.error('获取文档列表错误:', error);
    res.status(500).json({
      success: false,
      message: '获取文档列表失败',
      error: error.message
    });
  }
}

// 获取文档详细内容
async function getDocumentContent(req, res) {
  try {
    const { id } = req.params;
    
    const document = await Document.findById(id)
      .select('originalName fileSize uploadedAt protocolType extractedText sectionedText tables assessmentSchedule parseInfo');
    
    if (!document) {
      return res.status(404).json({
        success: false,
        message: '文档不存在'
      });
    }

    res.json({
      success: true,
      message: '获取文档内容成功',
      document: {
        _id: document._id,
        originalName: document.originalName,
        fileSize: document.fileSize,
        uploadedAt: document.uploadedAt,
        protocolType: document.protocolType,
        parseInfo: document.parseInfo,
        content: {
          extractedText: document.extractedText,
          sections: document.sectionedText || [],
          tables: document.tables || [],
          assessmentSchedule: document.assessmentSchedule || null
        }
      }
    });
    
  } catch (error) {
    console.error('获取文档内容错误:', error);
    res.status(500).json({
      success: false,
      message: '获取文档内容失败',
      error: error.message
    });
  }
}

// 导出评估时间表
async function exportAssessmentSchedule(req, res) {
  try {
    const { id } = req.params;
    const document = await Document.findById(id);

    if (!document) {
      return res.status(404).json({
        success: false,
        message: '文档不存在'
      });
    }

    if (!document.assessmentSchedule || !document.assessmentSchedule.htmlContent) {
      return res.status(400).json({
        success: false,
        message: '文档中未找到评估时间表'
      });
    }

    console.log('📊 开始手动导出评估时间表...');
    
    const targetDir = path.join(__dirname, '..', 'ScheduleOfAssessment');
    const result = exportAssessmentScheduleToExcel(
      document.assessmentSchedule.htmlContent,
      document.originalName,
      targetDir
    );

    res.json({
      success: true,
      message: '评估时间表导出成功',
      fileName: result.fileName,
      filePath: result.filePath,
      rowsCount: result.rowsCount,
      columnsCount: result.columnsCount
    });

  } catch (error) {
    console.error('❌ 导出评估时间表失败:', error);
    res.status(500).json({
      success: false,
      message: '导出评估时间表失败',
      error: error.message
    });
  }
}

// 确认SDTM分析结果
async function confirmSDTMAnalysis(req, res) {
  try {
    const { id } = req.params;
    const { procedures, mappings, summary } = req.body;

    console.log(`确认文档 ${id} 的SDTM分析结果`);

    const document = await Document.findById(id);
    if (!document) {
      return res.status(404).json({
        success: false,
        message: '文档不存在'
      });
    }

    // 更新用户确认的SDTM数据
    document.userConfirmedSdtm = {
      procedures,
      mappings,
      summary,
      confirmedAt: new Date()
    };
    
    // 更新状态
    document.sdtmAnalysisStatus = 'confirmed';

    await document.save();

    console.log('SDTM分析结果已确认并保存');

    res.json({
      success: true,
      message: 'SDTM分析结果已确认并保存',
      data: {
        documentId: id,
        confirmedAt: document.userConfirmedSdtm.confirmedAt,
        status: document.sdtmAnalysisStatus
      }
    });

  } catch (error) {
    console.error('确认SDTM分析结果错误:', error);
    res.status(500).json({
      success: false,
      message: '确认SDTM分析结果失败',
      error: error.message
    });
  }
}

module.exports = {
  uploadDocument,
  getDocuments,
  getDocumentContent,
  exportAssessmentSchedule,
  confirmSDTMAnalysis
}; 